import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/mine.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0 md:pt-16 sm:pt-8 xs:!px-4'>
          <div className="flex items-center justify-between w-full lg:flex-col lg:gap-8">
            {/* Image Section - Left side on desktop, top on mobile */}
            <div className='w-1/2 lg:w-full flex justify-center'>
              <div className='relative w-96 h-96 xl:w-80 xl:h-80 lg:w-72 lg:h-72 md:w-56 md:h-56 sm:w-44 sm:h-44 xs:w-36 xs:h-36 rounded-full overflow-hidden border-4 border-solid border-dark dark:border-light shadow-2xl sm:border-2'>
                <Image 
                  src={profilePic} 
                  alt='Bright' 
                  fill
                  className='w-full h-full object-cover'
                  priority
                  sizes='(max-width: 479px) 144px,
                         (max-width: 640px) 176px,
                         (max-width: 768px) 224px,
                         (max-width: 1024px) 288px,
                         (max-width: 1280px) 320px,
                         384px'
                />
              </div>
            </div>

            {/* Content Section - Right side on desktop, full width on mobile */}
            <div className='w-1/2 lg:w-full flex flex-col items-start self-center lg:items-center lg:text-center'>
              <AnimatedText 
                text="Turning Vision Into Reality With Code And Design." 
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-4xl sm:!text-3xl xs:!text-2xl' 
              />
              <p className='my-4 text-base font-medium lg:text-center md:text-sm sm:text-xs'>
                Full-stack developer crafting modern, secure, and scalable web applications using React, Vue, Angular, Node.js, Laravel, and more. Turning ideas into powerful digital experiences.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center sm:flex-col sm:w-full sm:gap-3'>
                <Link 
                  href="/Bright.html" 
                  target='_blank' 
                  className='flex items-center justify-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent dark:bg-light dark:text-dark hover:border-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base sm:w-full sm:py-3'
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1 sm:w-5"}/>                
                </Link>
                <Link 
                  href="mailto:obiorahbrightifenna@gmail.com" 
                  target={'_blank'}
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base sm:ml-0 sm:w-full sm:text-center'
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        
        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24 lg:hidden'>
          <Image src={lightBulb} alt="Bright" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}